# Project 3 : Using Folium Library for Geographic Overlays

In [2]:
import folium
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
country_geo = 'data/world-countries.json'

In [8]:
#Let us read the dataset
import pandas as pd

df = pd.read_csv("Indicators", on_bad_lines='skip', engine='python')

print(df.shape)
df.head()

(5808876, 6)

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960.0,1.335609e+02
1,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960.0,8.779760e+01
2,Arab World,ARB,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960.0,6.634579e+00
3,Arab World,ARB,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960.0,8.102333e+01
4,Arab World,ARB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,1960.0,3.000000e+06

In [10]:
# Select CO2 emissions for all countries in 2011

hist_indicator = r'CO2 emissions \(metric'
hist_year = 2011

mask1 = df['IndicatorName'].str.contains(hist_indicator, na=False)
mask2 = df['Year'] == hist_year

co2_2011 = df[mask1 & mask2]

print(co2_2011.shape)
co2_2011.head()

(232, 6)

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
5178693,Arab World,ARB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,4.724500
5179206,Caribbean small states,CSS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,9.692960
5179713,Central Europe and the Baltics,CEB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,6.911131
5180288,East Asia & Pacific (all income levels),EAS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,5.859548
5180874,East Asia & Pacific (developing only),EAP,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,5.302499

In [12]:
stage = df[
    (df['IndicatorName'] == 'CO2 emissions (metric tons per capita)') &
    (df['Year'] == 2011)
]

print(stage.shape)
stage.head()

(232, 6)

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
5178693,Arab World,ARB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,4.724500
5179206,Caribbean small states,CSS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,9.692960
5179713,Central Europe and the Baltics,CEB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,6.911131
5180288,East Asia & Pacific (all income levels),EAS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,5.859548
5180874,East Asia & Pacific (developing only),EAP,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2011.0,5.302499

In [14]:
#Setup the data for plotting
#Create a data frame with just the country codes and the values we want to be
#plotted.
plot_data = stage[['CountryCode','Value']]
plot_data.head()

        CountryCode     Value
5178693         ARB  4.724500
5179206         CSS  9.692960
5179713         CEB  6.911131
5180288         EAS  5.859548
5180874         EAP  5.302499

In [15]:
# Label for the legend
hist_indicator = stage.iloc[0]['IndicatorName']
print(hist_indicator)

CO2 emissions (metric tons per capita)

In [16]:
#Visualize CO2 emissions per capita using Folium
#Folium provides interactive maps with the ability to create sophisticated
# overlays for data visualization
#Setup a folium map at a high-level zoom.
map = folium.Map(location=[100, 0], zoom_start=1.5)

In [19]:
import folium

country_geo = 'world-countries.json'  # adjust path

m = folium.Map(location=[20, 0], zoom_start=2)

folium.Choropleth(
    geo_data=country_geo,
    data=plot_data,
    columns=['CountryCode', 'Value'],
    key_on='feature.id',
    fill_color='YlGnBu'
).add_to(m)

m.save("co2_map.html")

In [21]:
from IPython.display import HTML
HTML('<iframe src=co2_map.html width=700 height=450></iframe>')